version: '3.8'

services:
  php:
    container_name: wunder-checkout
    build:
      context: .
    image: checkout-wunder-mobility
    ports:
      - 8010:8000
    volumes:
    - .:/app
    #- /app/var
    #- /app/vendor
    #- /app/node_modules
    #- /app/public/build
    command: php -S 0.0.0.0:8000 -t public/
